// ============================================================
// SITE CONFIGURATION — Edit all content here
// ============================================================

export const SITE_CONFIG = {
  brandName: "Yonatan Web Studio",
  ownerName: "Yonatan Sherer",
  email: "yonatansh103@gmail.com",
  whatsapp: "https://wa.me/972542490335",
  line: "https://line.me/ti/p/vJzaJqx8pt",
  phone: "+972542490335",
  linkedin: "https://www.linkedin.com/in/yonatan-sherer",
  github: "https://github.com/YonatanSherer",
  portfolio: "https://yonatansherer.netlify.app",
  facebook: "#",
  instagram: "#",
  location: "Available remotely / Thailand / Israel / Worldwide",
  // Analytics IDs (add when ready)
  googleAnalyticsId: "",
  metaPixelId: "",
};

export const NAV_LINKS = [
  { id: "home", en: "Home", he: "בית", th: "หน้าแรก" },
  { id: "services", en: "Services", he: "שירותים", th: "บริการ" },
  { id: "packages", en: "Packages", he: "חבילות", th: "แพ็คเกจ" },
  { id: "process", en: "Process", he: "תהליך", th: "ขั้นตอน" },
  { id: "portfolio", en: "Portfolio", he: "תיק עבודות", th: "ผลงาน" },
  { id: "faq", en: "FAQ", he: "שאלות נפוצות", th: "คำถามที่พบบ่อย" },
  { id: "contact", en: "Contact", he: "צור קשר", th: "ติดต่อ" },
];

// ============================================================
// MULTILINGUAL CONTENT
// ============================================================

export const CONTENT = {
  en: {
    // Hero
    heroHeadline: "Modern Websites for Small Businesses That Want More Customers",
    heroSubheadline: "I build responsive websites, landing pages, and simple web apps that help businesses look professional, explain their services clearly, and receive more inquiries through WhatsApp, LINE, email, and contact forms.",
    heroCta1: "Get a Free Quote",
    heroCta2: "View Packages",
    heroTrust: [
      "Mobile-Friendly",
      "Fast Delivery",
      "Multilingual Options",
      "Clean Design",
    ],

    // Trust Strip
    trustPoints: [
      { title: "Responsive Design", desc: "Looks great on mobile and desktop" },
      { title: "Business-Focused", desc: "Built for real business inquiries" },
      { title: "Multilingual", desc: "English, Hebrew, Thai and more" },
      { title: "Clear Process", desc: "Transparent pricing, simple steps" },
    ],

    // Services
    servicesTitle: "What I Build",
    servicesSubtitle: "Professional digital solutions tailored for small businesses",
    services: [
      {
        title: "Landing Pages",
        desc: "One-page websites designed for campaigns, personal brands, service businesses, and quick customer inquiries.",
        icon: "Layout",
      },
      {
        title: "Business Websites",
        desc: "Professional websites with pages such as Home, About, Services, Gallery, Testimonials, and Contact.",
        icon: "Globe",
      },
      {
        title: "Multilingual Websites",
        desc: "Websites in English, Hebrew, Thai, or other language combinations, useful for businesses that serve international customers.",
        icon: "Languages",
      },
      {
        title: "Small Web Apps",
        desc: "Simple custom tools such as booking forms, dashboards, calculators, admin panels, and customer request systems.",
        icon: "AppWindow",
      },
      {
        title: "Website Redesign",
        desc: "Improve an old or outdated website with a cleaner design, better mobile experience, and stronger messaging.",
        icon: "RefreshCw",
      },
      {
        title: "Maintenance & Updates",
        desc: "Ongoing support for small changes, content updates, technical fixes, and improvements.",
        icon: "Wrench",
      },
    ],
    servicesCta: "Ask About This Service",

    // Packages
    packagesTitle: "Packages & Pricing",
    packagesSubtitle: "Clear starting prices for every business need",
    packagesNote: "Final price depends on the number of pages, languages, content, design complexity, integrations, and required features.",
    packages: [
      {
        name: "Landing Page",
        price: "₪1,500",
        bestFor: "Small businesses that need a quick online presence.",
        features: [
          "One-page website",
          "Mobile responsive design",
          "WhatsApp / LINE contact buttons",
          "Contact form",
          "Basic SEO setup",
          "Social media links",
          "Deployment guidance",
        ],
        cta: "Start with a Landing Page",
        popular: false,
      },
      {
        name: "Business Website",
        price: "₪3,500",
        bestFor: "Businesses that need a complete professional website.",
        features: [
          "4–6 sections or pages",
          "Home, About, Services, Contact",
          "Mobile responsive design",
          "Image gallery or portfolio section",
          "Contact form",
          "WhatsApp / LINE buttons",
          "Basic SEO setup",
          "Google Maps integration",
          "Deployment guidance",
        ],
        cta: "Build My Business Website",
        popular: true,
      },
      {
        name: "Multilingual / Advanced",
        price: "₪5,500",
        bestFor: "Businesses that serve local and international customers.",
        features: [
          "Everything in Business Website",
          "Two-language structure",
          "Language switcher",
          "Bilingual content layout",
          "Conversion-focused sections",
          "Advanced UI components",
          "Optional booking or inquiry form",
          "Basic analytics setup",
        ],
        cta: "Create a Multilingual Website",
        popular: false,
      },
    ],

    // Add-ons
    addonsTitle: "Add-Ons",
    addonsSubtitle: "Customize your project with additional features",
    addons: [
      "Extra language",
      "Extra page",
      "Logo / simple branding",
      "Copywriting assistance",
      "Blog setup",
      "Booking system",
      "Admin dashboard",
      "Payment integration",
      "Google Analytics setup",
      "SEO content optimization",
      "Monthly maintenance",
    ],

    // Process
    processTitle: "How It Works",
    processSubtitle: "A simple, clear process from idea to launch",
    processSteps: [
      { title: "Discovery", desc: "We understand your business, goals, target audience, and required website features." },
      { title: "Structure & Design", desc: "I create the website structure, sections, and design direction." },
      { title: "Build & Review", desc: "The website is built, reviewed, and improved based on your feedback." },
      { title: "Launch & Support", desc: "The website goes live, and I can provide ongoing updates and support." },
    ],

    // Portfolio
    portfolioTitle: "Selected Work & Project Examples",
    portfolioSubtitle: "Examples of the types of projects I build",
    portfolioItems: [
      {
        title: "Business Website Example",
        category: "Website",
        desc: "A clean website for a local business with service sections, contact buttons, and responsive design.",
        cta: "Coming Soon",
      },
      {
        title: "Multilingual Website Example",
        category: "Multilingual Website",
        desc: "A website prepared for businesses that need English and Thai content.",
        cta: "Coming Soon",
      },
      {
        title: "Web App Example",
        category: "Web App",
        desc: "A simple web app with forms, dashboard-style layout, and user-friendly interactions.",
        cta: "Coming Soon",
      },
      {
        title: "Personal Portfolio Example",
        category: "Portfolio",
        desc: "A modern portfolio website for professionals who want to showcase skills and projects.",
        cta: "Coming Soon",
      },
    ],

    // Why Me
    whyMeTitle: "Why Work With Me?",
    whyMeParagraph: "I combine software engineering skills with practical business thinking. My goal is not only to build a nice-looking website, but to create a clear and professional online presence that helps customers understand your business and contact you easily.",
    whyMePoints: [
      "Software Engineering background",
      "Experience building real applications, not only static pages",
      "Ability to build websites and simple web apps",
      "Clean and mobile-friendly design",
      "Clear communication",
      "Support for multilingual and international-facing businesses",
      "Focus on practical results: more trust, more inquiries, better online presence",
    ],

    // Testimonials
    testimonialsTitle: "What Clients Say",
    testimonials: [
      { text: "Client testimonial coming soon", author: "— Coming soon" },
      { text: "Business owner feedback coming soon", author: "— Coming soon" },
      { text: "Project review coming soon", author: "— Coming soon" },
    ],

    // FAQ
    faqTitle: "Frequently Asked Questions",
    faqItems: [
      { q: "How much does a website cost?", a: "It depends on the number of pages, languages, design complexity, and features. Landing pages usually start from ₪1,500, business websites from ₪3,500, and multilingual or advanced websites from ₪5,500." },
      { q: "How long does it take to build a website?", a: "A simple landing page can usually be completed faster than a full business website. The timeline depends on content readiness, number of revisions, and required features." },
      { q: "Do I need to provide the text and images?", a: "You can provide your own content, or I can help organize and improve the text. Professional photos are recommended, but placeholders can be used at the beginning." },
      { q: "Can you build the website in more than one language?", a: "Yes. I can create multilingual website structures such as English and Hebrew, English and Thai, or other combinations." },
      { q: "Can you maintain the website after launch?", a: "Yes. Monthly maintenance can include small updates, fixes, text changes, image changes, and improvements." },
      { q: "Do you build only websites?", a: "No. I can also build simple web apps, forms, dashboards, calculators, and custom digital tools for businesses." },
      { q: "Is hosting and domain included?", a: "Hosting and domain costs are usually paid separately by the client, but I can guide the setup process." },
    ],

    // Contact
    contactTitle: "Ready to Build Your Website?",
    contactSubtitle: "Send me a message and tell me what kind of website your business needs. I will reply with the next steps and a clear quote.",
    contactForm: {
      fullName: "Full Name",
      businessName: "Business Name",
      email: "Email",
      phone: "Phone / WhatsApp",
      preferredContact: "Preferred Contact Method",
      contactMethods: ["WhatsApp", "LINE", "Email", "Phone"],
      websiteType: "Type of Website Needed",
      websiteTypes: ["Landing page", "Business website", "Multilingual website", "Web app", "Redesign", "Not sure yet"],
      budget: "Estimated Budget",
      budgets: ["Under ₪2,000", "₪2,000–₪5,000", "₪5,000–₪10,000", "₪10,000+", "Not sure yet"],
      message: "Message",
      submit: "Send Message",
      success: "Thank you! Your message was received. I will get back to you soon.",
    },

    // Final CTA
    finalCtaHeadline: "Let's Turn Your Business Into a Professional Online Presence",
    finalCta1: "Get a Free Quote",
    finalCta2: "Message on WhatsApp",
    finalCta3: "Message on LINE",

    // Footer
    footerTagline: "Websites, landing pages, and simple web apps for small businesses.",
    footerCopyright: `© ${new Date().getFullYear()} Yonatan Web Studio. All rights reserved.`,
  },

  he: {
    heroHeadline: "אתרים מודרניים לעסקים קטנים שרוצים יותר לקוחות",
    heroSubheadline: "אני בונה אתרים רספונסיביים, דפי נחיתה ואפליקציות ווב פשוטות שעוזרים לעסקים להיראות מקצועיים, להסביר את השירותים שלהם בבהירות ולקבל יותר פניות דרך וואטסאפ, LINE, אימייל וטפסי יצירת קשר.",
    heroCta1: "קבלו הצעת מחיר חינם",
    heroCta2: "צפו בחבילות",
    heroTrust: [
      "מותאם למובייל",
      "אספקה מהירה",
      "אפשרויות רב-לשוניות",
      "עיצוב נקי",
    ],
    trustPoints: [
      { title: "עיצוב רספונסיבי", desc: "נראה מעולה בנייד ובמחשב" },
      { title: "ממוקד עסקית", desc: "בנוי עבור פניות עסקיות אמיתיות" },
      { title: "רב-לשוני", desc: "אנגלית, עברית, תאית ועוד" },
      { title: "תהליך ברור", desc: "תמחור שקוף, שלבים פשוטים" },
    ],
    servicesTitle: "מה אני בונה",
    servicesSubtitle: "פתרונות דיגיטליים מקצועיים המותאמים לעסקים קטנים",
    services: [
      { title: "דפי נחיתה", desc: "אתרי עמוד אחד המעוצבים עבור קמפיינים, מותגים אישיים, עסקי שירות ופניות מהירות של לקוחות.", icon: "Layout" },
      { title: "אתרים עסקיים", desc: "אתרים מקצועיים עם עמודים כמו בית, אודות, שירותים, גלריה, המלצות ויצירת קשר.", icon: "Globe" },
      { title: "אתרים רב-לשוניים", desc: "אתרים באנגלית, עברית, תאית או שפות אחרות, מתאימים לעסקים שמשרתים לקוחות בינלאומיים.", icon: "Languages" },
      { title: "אפליקציות ווב קטנות", desc: "כלים מותאמים אישית כגון טפסי הזמנה, לוחות מחוונים, מחשבונים ומערכות ניהול.", icon: "AppWindow" },
      { title: "עיצוב מחדש", desc: "שיפור אתר ישן או מיושן עם עיצוב נקי יותר, חוויית מובייל טובה יותר ומסרים חזקים יותר.", icon: "RefreshCw" },
      { title: "תחזוקה ועדכונים", desc: "תמיכה שוטפת לשינויים קטנים, עדכוני תוכן, תיקונים טכניים ושיפורים.", icon: "Wrench" },
    ],
    servicesCta: "שאלו על שירות זה",
    packagesTitle: "חבילות ותמחור",
    packagesSubtitle: "מחירי התחלה ברורים לכל צורך עסקי",
    packagesNote: "המחיר הסופי תלוי בהיקף הפרויקט, מספר העמודים, שפות, תוכן, מורכבות העיצוב, אינטגרציות ותכונות נדרשות.",
    packages: [
      {
        name: "דף נחיתה",
        price: "₪1,500",
        bestFor: "עסקים קטנים שצריכים נוכחות מקוונת מהירה.",
        features: ["אתר עמוד אחד", "עיצוב רספונסיבי למובייל", "כפתורי וואטסאפ / LINE", "טופס יצירת קשר", "הגדרת SEO בסיסית", "קישורי רשתות חברתיות", "הדרכת העלאה"],
        cta: "התחילו עם דף נחיתה",
        popular: false,
      },
      {
        name: "אתר עסקי",
        price: "₪3,500",
        bestFor: "עסקים שצריכים אתר מקצועי מלא.",
        features: ["4–6 מקטעים או עמודים", "בית, אודות, שירותים, יצירת קשר", "עיצוב רספונסיבי", "גלריה או מקטע תיק עבודות", "טופס יצירת קשר", "כפתורי וואטסאפ / LINE", "SEO בסיסי", "שילוב Google Maps", "הדרכת העלאה"],
        cta: "בנו את האתר העסקי שלי",
        popular: true,
      },
      {
        name: "רב-לשוני / מתקדם",
        price: "₪5,500",
        bestFor: "עסקים שמשרתים לקוחות מקומיים ובינלאומיים.",
        features: ["כל מה שבאתר העסקי", "מבנה בשתי שפות", "מתג שפות", "פריסת תוכן דו-לשונית", "מקטעים ממוקדי המרה", "רכיבי UI מתקדמים", "טופס הזמנה או פנייה אופציונלי", "הגדרת אנליטיקס בסיסית"],
        cta: "צרו אתר רב-לשוני",
        popular: false,
      },
    ],
    addonsTitle: "תוספות",
    addonsSubtitle: "התאימו את הפרויקט עם תכונות נוספות",
    addons: ["שפה נוספת", "עמוד נוסף", "לוגו / מיתוג פשוט", "סיוע בכתיבת תוכן", "הקמת בלוג", "מערכת הזמנות", "לוח ניהול", "שילוב תשלומים", "הגדרת Google Analytics", "אופטימיזציית תוכן SEO", "תחזוקה חודשית"],
    processTitle: "איך זה עובד",
    processSubtitle: "תהליך פשוט וברור מרעיון להשקה",
    processSteps: [
      { title: "גילוי", desc: "אנחנו מבינים את העסק שלכם, המטרות, קהל היעד והתכונות הנדרשות." },
      { title: "מבנה ועיצוב", desc: "אני יוצר את מבנה האתר, המקטעים וכיוון העיצוב." },
      { title: "בנייה וסקירה", desc: "האתר נבנה, נבדק ומשופר בהתאם למשוב שלכם." },
      { title: "השקה ותמיכה", desc: "האתר עולה לאוויר, ואני יכול לספק עדכונים ותמיכה שוטפים." },
    ],
    portfolioTitle: "עבודות נבחרות ודוגמאות פרויקטים",
    portfolioSubtitle: "דוגמאות לסוגי הפרויקטים שאני בונה",
    portfolioItems: [
      { title: "דוגמת אתר עסקי", category: "אתר", desc: "אתר נקי לעסק מקומי עם מקטעי שירות, כפתורי יצירת קשר ועיצוב רספונסיבי.", cta: "בקרוב" },
      { title: "דוגמת אתר רב-לשוני", category: "אתר רב-לשוני", desc: "אתר שהוכן לעסקים שצריכים תוכן באנגלית ותאית.", cta: "בקרוב" },
      { title: "דוגמת אפליקציית ווב", category: "אפליקציית ווב", desc: "אפליקציית ווב פשוטה עם טפסים, פריסת לוח מחוונים ואינטראקציות ידידותיות.", cta: "בקרוב" },
      { title: "דוגמת תיק עבודות אישי", category: "תיק עבודות", desc: "אתר תיק עבודות מודרני לאנשי מקצוע שרוצים להציג כישורים ופרויקטים.", cta: "בקרוב" },
    ],
    whyMeTitle: "למה לעבוד איתי?",
    whyMeParagraph: "אני משלב כישורי הנדסת תוכנה עם חשיבה עסקית מעשית. המטרה שלי היא לא רק לבנות אתר יפה, אלא ליצור נוכחות מקוונת ברורה ומקצועית שעוזרת ללקוחות להבין את העסק שלכם וליצור קשר בקלות.",
    whyMePoints: [
      "רקע בהנדסת תוכנה",
      "ניסיון בבניית אפליקציות אמיתיות, לא רק עמודים סטטיים",
      "יכולת לבנות אתרים ואפליקציות ווב פשוטות",
      "עיצוב נקי וידידותי למובייל",
      "תקשורת ברורה",
      "תמיכה בעסקים רב-לשוניים ובינלאומיים",
      "מיקוד בתוצאות מעשיות: יותר אמון, יותר פניות, נוכחות מקוונת טובה יותר",
    ],
    testimonialsTitle: "מה לקוחות אומרים",
    testimonials: [
      { text: "המלצת לקוח תגיע בקרוב", author: "— בקרוב" },
      { text: "משוב בעל עסק יגיע בקרוב", author: "— בקרוב" },
      { text: "סקירת פרויקט תגיע בקרוב", author: "— בקרוב" },
    ],
    faqTitle: "שאלות נפוצות",
    faqItems: [
      { q: "כמה עולה אתר?", a: "זה תלוי במספר העמודים, שפות, מורכבות העיצוב והתכונות. דפי נחיתה מתחילים מ-₪1,500, אתרים עסקיים מ-₪3,500 ואתרים רב-לשוניים או מתקדמים מ-₪5,500." },
      { q: "כמה זמן לוקח לבנות אתר?", a: "דף נחיתה פשוט יכול להסתיים מהר יותר מאתר עסקי מלא. לוח הזמנים תלוי במוכנות התוכן, מספר התיקונים והתכונות הנדרשות." },
      { q: "האם אני צריך לספק את הטקסט והתמונות?", a: "תוכלו לספק תוכן משלכם, או שאוכל לעזור לארגן ולשפר את הטקסט. תמונות מקצועיות מומלצות, אך ניתן להשתמש בתמונות מציינות מקום בהתחלה." },
      { q: "האם אתה יכול לבנות אתר ביותר משפה אחת?", a: "כן. אני יכול ליצור מבני אתרים רב-לשוניים כגון אנגלית ועברית, אנגלית ותאית, או שילובים אחרים." },
      { q: "האם אתה יכול לתחזק את האתר לאחר ההשקה?", a: "כן. תחזוקה חודשית יכולה לכלול עדכונים קטנים, תיקונים, שינויי טקסט, שינויי תמונות ושיפורים." },
      { q: "האם אתה בונה רק אתרים?", a: "לא. אני גם יכול לבנות אפליקציות ווב פשוטות, טפסים, לוחות מחוונים, מחשבונים וכלים דיגיטליים מותאמים לעסקים." },
      { q: "האם אירוח ודומיין כלולים?", a: "עלויות אירוח ודומיין בדרך כלל משולמות בנפרד על ידי הלקוח, אך אני יכול להדריך בתהליך ההגדרה." },
    ],
    contactTitle: "מוכנים לבנות את האתר שלכם?",
    contactSubtitle: "שלחו לי הודעה וספרו לי איזה סוג אתר העסק שלכם צריך. אחזור אליכם עם השלבים הבאים והצעת מחיר ברורה.",
    contactForm: {
      fullName: "שם מלא",
      businessName: "שם העסק",
      email: "אימייל",
      phone: "טלפון / וואטסאפ",
      preferredContact: "שיטת קשר מועדפת",
      contactMethods: ["וואטסאפ", "LINE", "אימייל", "טלפון"],
      websiteType: "סוג האתר הנדרש",
      websiteTypes: ["דף נחיתה", "אתר עסקי", "אתר רב-לשוני", "אפליקציית ווב", "עיצוב מחדש", "עדיין לא בטוח"],
      budget: "תקציב משוער",
      budgets: ["מתחת ל-₪2,000", "₪2,000–₪5,000", "₪5,000–₪10,000", "₪10,000+", "עדיין לא בטוח"],
      message: "הודעה",
      submit: "שלחו הודעה",
      success: "תודה! ההודעה התקבלה. אחזור אליכם בהקדם.",
    },
    finalCtaHeadline: "בואו נהפוך את העסק שלכם לנוכחות מקוונת מקצועית",
    finalCta1: "קבלו הצעת מחיר חינם",
    finalCta2: "שלחו הודעה בוואטסאפ",
    finalCta3: "שלחו הודעה ב-LINE",
    footerTagline: "אתרים, דפי נחיתה ואפליקציות ווב פשוטות לעסקים קטנים.",
    footerCopyright: `© ${new Date().getFullYear()} Yonatan Web Studio. כל הזכויות שמורות.`,
  },

  th: {
    heroHeadline: "เว็บไซต์สมัยใหม่สำหรับธุรกิจขนาดเล็กที่ต้องการลูกค้ามากขึ้น",
    heroSubheadline: "ผมสร้างเว็บไซต์ที่ตอบสนองทุกอุปกรณ์ แลนดิ้งเพจ และเว็บแอปง่ายๆ ที่ช่วยให้ธุรกิจดูเป็นมืออาชีพ อธิบายบริการได้ชัดเจน และรับการติดต่อมากขึ้นผ่าน WhatsApp, LINE, อีเมล และแบบฟอร์มติดต่อ",
    heroCta1: "ขอใบเสนอราคาฟรี",
    heroCta2: "ดูแพ็คเกจ",
    heroTrust: [
      "รองรับมือถือ",
      "ส่งมอบรวดเร็ว",
      "รองรับหลายภาษา",
      "ออกแบบสะอาด",
    ],
    trustPoints: [
      { title: "ออกแบบ Responsive", desc: "ดูดีทั้งบนมือถือและเดสก์ท็อป" },
      { title: "เน้นธุรกิจ", desc: "สร้างมาเพื่อการติดต่อธุรกิจจริง" },
      { title: "หลายภาษา", desc: "อังกฤษ ฮีบรู ไทย และอื่นๆ" },
      { title: "กระบวนการชัดเจน", desc: "ราคาโปร่งใส ขั้นตอนง่าย" },
    ],
    servicesTitle: "สิ่งที่ผมสร้าง",
    servicesSubtitle: "โซลูชันดิจิทัลมืออาชีพที่ออกแบบมาสำหรับธุรกิจขนาดเล็ก",
    services: [
      { title: "แลนดิ้งเพจ", desc: "เว็บไซต์หน้าเดียวที่ออกแบบมาสำหรับแคมเปญ แบรนด์ส่วนตัว ธุรกิจบริการ และการติดต่อลูกค้าอย่างรวดเร็ว", icon: "Layout" },
      { title: "เว็บไซต์ธุรกิจ", desc: "เว็บไซต์มืออาชีพพร้อมหน้าต่างๆ เช่น หน้าแรก เกี่ยวกับ บริการ แกลเลอรี รีวิว และติดต่อ", icon: "Globe" },
      { title: "เว็บไซต์หลายภาษา", desc: "เว็บไซต์ภาษาอังกฤษ ฮีบรู ไทย หรือภาษาอื่นๆ เหมาะสำหรับธุรกิจที่ให้บริการลูกค้าต่างประเทศ", icon: "Languages" },
      { title: "เว็บแอปขนาดเล็ก", desc: "เครื่องมือที่กำหนดเอง เช่น แบบฟอร์มจอง แดชบอร์ด เครื่องคิดเลข แผงควบคุม และระบบคำขอลูกค้า", icon: "AppWindow" },
      { title: "ออกแบบเว็บไซต์ใหม่", desc: "ปรับปรุงเว็บไซต์เก่าหรือล้าสมัยด้วยการออกแบบที่สะอาดขึ้น ประสบการณ์มือถือที่ดีขึ้น และข้อความที่แข็งแกร่งขึ้น", icon: "RefreshCw" },
      { title: "บำรุงรักษาและอัปเดต", desc: "การสนับสนุนอย่างต่อเนื่องสำหรับการเปลี่ยนแปลงเล็กน้อย การอัปเดตเนื้อหา การแก้ไขทางเทคนิค และการปรับปรุง", icon: "Wrench" },
    ],
    servicesCta: "สอบถามเกี่ยวกับบริการนี้",
    packagesTitle: "แพ็คเกจและราคา",
    packagesSubtitle: "ราคาเริ่มต้นที่ชัดเจนสำหรับทุกความต้องการของธุรกิจ",
    packagesNote: "ราคาสุดท้ายขึ้นอยู่กับจำนวนหน้า ภาษา เนื้อหา ความซับซ้อนของการออกแบบ การผสานรวม และฟีเจอร์ที่ต้องการ",
    packages: [
      {
        name: "แลนดิ้งเพจ",
        price: "₪1,500",
        bestFor: "ธุรกิจขนาดเล็กที่ต้องการตัวตนออนไลน์อย่างรวดเร็ว",
        features: ["เว็บไซต์หน้าเดียว", "ออกแบบรองรับมือถือ", "ปุ่ม WhatsApp / LINE", "แบบฟอร์มติดต่อ", "ตั้งค่า SEO พื้นฐาน", "ลิงก์โซเชียลมีเดีย", "คำแนะนำการ Deploy"],
        cta: "เริ่มต้นด้วยแลนดิ้งเพจ",
        popular: false,
      },
      {
        name: "เว็บไซต์ธุรกิจ",
        price: "₪3,500",
        bestFor: "ธุรกิจที่ต้องการเว็บไซต์มืออาชีพที่สมบูรณ์",
        features: ["4–6 ส่วนหรือหน้า", "หน้าแรก เกี่ยวกับ บริการ ติดต่อ", "ออกแบบรองรับมือถือ", "แกลเลอรีหรือส่วนผลงาน", "แบบฟอร์มติดต่อ", "ปุ่ม WhatsApp / LINE", "SEO พื้นฐาน", "Google Maps", "คำแนะนำการ Deploy"],
        cta: "สร้างเว็บไซต์ธุรกิจของฉัน",
        popular: true,
      },
      {
        name: "หลายภาษา / ขั้นสูง",
        price: "₪5,500",
        bestFor: "ธุรกิจที่ให้บริการลูกค้าในประเทศและต่างประเทศ",
        features: ["ทุกอย่างในเว็บไซต์ธุรกิจ", "โครงสร้างสองภาษา", "ตัวสลับภาษา", "เลย์เอาท์เนื้อหาสองภาษา", "ส่วนที่เน้นการแปลง", "ส่วนประกอบ UI ขั้นสูง", "แบบฟอร์มจองหรือสอบถาม", "ตั้งค่า Analytics พื้นฐาน"],
        cta: "สร้างเว็บไซต์หลายภาษา",
        popular: false,
      },
    ],
    addonsTitle: "ส่วนเสริม",
    addonsSubtitle: "ปรับแต่งโปรเจ็กต์ของคุณด้วยฟีเจอร์เพิ่มเติม",
    addons: ["ภาษาเพิ่มเติม", "หน้าเพิ่มเติม", "โลโก้ / แบรนด์ง่ายๆ", "ช่วยเขียนเนื้อหา", "ตั้งค่าบล็อก", "ระบบจอง", "แดชบอร์ดผู้ดูแล", "ผสานระบบชำระเงิน", "ตั้งค่า Google Analytics", "เพิ่มประสิทธิภาพ SEO", "บำรุงรักษารายเดือน"],
    processTitle: "มันทำงานอย่างไร",
    processSubtitle: "กระบวนการที่ง่ายและชัดเจนจากไอเดียสู่การเปิดตัว",
    processSteps: [
      { title: "ค้นพบ", desc: "เราทำความเข้าใจธุรกิจ เป้าหมาย กลุ่มเป้าหมาย และฟีเจอร์เว็บไซต์ที่ต้องการ" },
      { title: "โครงสร้างและออกแบบ", desc: "ผมสร้างโครงสร้างเว็บไซต์ ส่วนต่างๆ และทิศทางการออกแบบ" },
      { title: "สร้างและรีวิว", desc: "เว็บไซต์ถูกสร้าง ตรวจสอบ และปรับปรุงตามข้อเสนอแนะของคุณ" },
      { title: "เปิดตัวและสนับสนุน", desc: "เว็บไซต์ขึ้นออนไลน์ และผมสามารถให้การอัปเดตและสนับสนุนอย่างต่อเนื่อง" },
    ],
    portfolioTitle: "ผลงานที่คัดสรรและตัวอย่างโปรเจ็กต์",
    portfolioSubtitle: "ตัวอย่างประเภทโปรเจ็กต์ที่ผมสร้าง",
    portfolioItems: [
      { title: "ตัวอย่างเว็บไซต์ธุรกิจ", category: "เว็บไซต์", desc: "เว็บไซต์สะอาดสำหรับธุรกิจท้องถิ่นพร้อมส่วนบริการ ปุ่มติดต่อ และการออกแบบ Responsive", cta: "เร็วๆ นี้" },
      { title: "ตัวอย่างเว็บไซต์หลายภาษา", category: "เว็บไซต์หลายภาษา", desc: "เว็บไซต์ที่เตรียมไว้สำหรับธุรกิจที่ต้องการเนื้อหาภาษาอังกฤษและไทย", cta: "เร็วๆ นี้" },
      { title: "ตัวอย่างเว็บแอป", category: "เว็บแอป", desc: "เว็บแอปง่ายๆ พร้อมแบบฟอร์ม เลย์เอาท์แบบแดชบอร์ด และอินเทอร์แอคชันที่ใช้งานง่าย", cta: "เร็วๆ นี้" },
      { title: "ตัวอย่างพอร์ตโฟลิโอส่วนตัว", category: "พอร์ตโฟลิโอ", desc: "เว็บไซต์พอร์ตโฟลิโอสมัยใหม่สำหรับมืออาชีพที่ต้องการแสดงทักษะและโปรเจ็กต์", cta: "เร็วๆ นี้" },
    ],
    whyMeTitle: "ทำไมต้องทำงานกับผม?",
    whyMeParagraph: "ผมผสมผสานทักษะวิศวกรรมซอฟต์แวร์กับการคิดเชิงธุรกิจที่ใช้ได้จริง เป้าหมายของผมไม่ใช่แค่สร้างเว็บไซต์ที่ดูดี แต่เพื่อสร้างตัวตนออนไลน์ที่ชัดเจนและเป็นมืออาชีพที่ช่วยให้ลูกค้าเข้าใจธุรกิจของคุณและติดต่อได้ง่าย",
    whyMePoints: [
      "พื้นฐานวิศวกรรมซอฟต์แวร์",
      "ประสบการณ์สร้างแอปพลิเคชันจริง ไม่ใช่แค่หน้าสแตติก",
      "ความสามารถในการสร้างเว็บไซต์และเว็บแอปง่ายๆ",
      "ออกแบบสะอาดและรองรับมือถือ",
      "สื่อสารชัดเจน",
      "สนับสนุนธุรกิจหลายภาษาและนานาชาติ",
      "เน้นผลลัพธ์ที่ใช้ได้จริง: ความน่าเชื่อถือมากขึ้น การติดต่อมากขึ้น ตัวตนออนไลน์ที่ดีขึ้น",
    ],
    testimonialsTitle: "ลูกค้าพูดว่าอะไร",
    testimonials: [
      { text: "รีวิวจากลูกค้าจะมาเร็วๆ นี้", author: "— เร็วๆ นี้" },
      { text: "ข้อเสนอแนะจากเจ้าของธุรกิจจะมาเร็วๆ นี้", author: "— เร็วๆ นี้" },
      { text: "รีวิวโปรเจ็กต์จะมาเร็วๆ นี้", author: "— เร็วๆ นี้" },
    ],
    faqTitle: "คำถามที่พบบ่อย",
    faqItems: [
      { q: "เว็บไซต์ราคาเท่าไหร่?", a: "ขึ้นอยู่กับจำนวนหน้า ภาษา ความซับซ้อนของการออกแบบ และฟีเจอร์ แลนดิ้งเพจเริ่มต้นที่ ₪1,500 เว็บไซต์ธุรกิจเริ่มต้นที่ ₪3,500 และเว็บไซต์หลายภาษาหรือขั้นสูงเริ่มต้นที่ ₪5,500" },
      { q: "ใช้เวลานานแค่ไหนในการสร้างเว็บไซต์?", a: "แลนดิ้งเพจง่ายๆ สามารถเสร็จได้เร็วกว่าเว็บไซต์ธุรกิจเต็มรูปแบบ ระยะเวลาขึ้นอยู่กับความพร้อมของเนื้อหา จำนวนการแก้ไข และฟีเจอร์ที่ต้องการ" },
      { q: "ฉันต้องจัดหาข้อความและรูปภาพเองไหม?", a: "คุณสามารถจัดหาเนื้อหาเอง หรือผมช่วยจัดระเบียบและปรับปรุงข้อความได้ แนะนำให้ใช้ภาพถ่ายมืออาชีพ แต่สามารถใช้ภาพแทนที่ได้ในตอนแรก" },
      { q: "คุณสร้างเว็บไซต์ได้มากกว่าหนึ่งภาษาไหม?", a: "ได้ ผมสามารถสร้างโครงสร้างเว็บไซต์หลายภาษา เช่น อังกฤษและฮีบรู อังกฤษและไทย หรือชุดภาษาอื่นๆ" },
      { q: "คุณดูแลเว็บไซต์หลังเปิดตัวได้ไหม?", a: "ได้ การบำรุงรักษารายเดือนรวมถึงการอัปเดตเล็กน้อย การแก้ไข การเปลี่ยนข้อความ การเปลี่ยนรูปภาพ และการปรับปรุง" },
      { q: "คุณสร้างแค่เว็บไซต์เท่านั้นไหม?", a: "ไม่ ผมยังสร้างเว็บแอปง่ายๆ แบบฟอร์ม แดชบอร์ด เครื่องคิดเลข และเครื่องมือดิจิทัลที่กำหนดเองสำหรับธุรกิจ" },
      { q: "โฮสติ้งและโดเมนรวมอยู่ไหม?", a: "ค่าโฮสติ้งและโดเมนมักจ่ายแยกโดยลูกค้า แต่ผมสามารถแนะนำกระบวนการตั้งค่าได้" },
    ],
    contactTitle: "พร้อมสร้างเว็บไซต์ของคุณหรือยัง?",
    contactSubtitle: "ส่งข้อความถึงผมและบอกว่าธุรกิจของคุณต้องการเว็บไซต์แบบไหน ผมจะตอบกลับพร้อมขั้นตอนถัดไปและใบเสนอราคาที่ชัดเจน",
    contactForm: {
      fullName: "ชื่อเต็ม",
      businessName: "ชื่อธุรกิจ",
      email: "อีเมล",
      phone: "โทรศัพท์ / WhatsApp",
      preferredContact: "วิธีการติดต่อที่ต้องการ",
      contactMethods: ["WhatsApp", "LINE", "อีเมล", "โทรศัพท์"],
      websiteType: "ประเภทเว็บไซต์ที่ต้องการ",
      websiteTypes: ["แลนดิ้งเพจ", "เว็บไซต์ธุรกิจ", "เว็บไซต์หลายภาษา", "เว็บแอป", "ออกแบบใหม่", "ยังไม่แน่ใจ"],
      budget: "งบประมาณโดยประมาณ",
      budgets: ["ต่ำกว่า ₪2,000", "₪2,000–₪5,000", "₪5,000–₪10,000", "₪10,000+", "ยังไม่แน่ใจ"],
      message: "ข้อความ",
      submit: "ส่งข้อความ",
      success: "ขอบคุณ! ข้อความของคุณถูกส่งแล้ว ผมจะติดต่อกลับเร็วๆ นี้",
    },
    finalCtaHeadline: "มาเปลี่ยนธุรกิจของคุณให้เป็นตัวตนออนไลน์ที่เป็นมืออาชีพ",
    finalCta1: "ขอใบเสนอราคาฟรี",
    finalCta2: "ส่งข้อความทาง WhatsApp",
    finalCta3: "ส่งข้อความทาง LINE",
    footerTagline: "เว็บไซต์ แลนดิ้งเพจ และเว็บแอปง่ายๆ สำหรับธุรกิจขนาดเล็ก",
    footerCopyright: `© ${new Date().getFullYear()} Yonatan Web Studio. สงวนลิขสิทธิ์`,
  },
};